FROM node:16-alpine

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn

ENV PATH /app/node_modules/.bin:$PATH

RUN mkdir server

WORKDIR /app/server

COPY . .

ENV NODE_ENV development

EXPOSE 5000

CMD ["yarn", "start"]